### ISSUE TITLE
Solidity compilation failed

### ISSUE THREAD

**Issue by ageorgios** [christoftorres/HoneyBadger#2]
Hello,

I get

CRITICAL:root:Solidity compilation failed
======= error =======
Solidity compilation failed

The sol is https://bscscan.com/address/0xbab5b27567ddbbc8f26017f9ed53fd65f731158d#code

**Comment by gsalzer** [comment]
Natively, Honeybadger uses a Solidity compiler for version 0.4.* that was current at the time when Honeybadger was developed. Your contract requires Solidity 0.5.*. Consider using [smartBugs](https://github.com/smartbugs/smartbugs), a framework for Ethereum analysis tools. Honeybadger is one of the supported tools. SmartBugs takes care that a Solidity compiler is used that matches the given Solidity source code. So your example should work with Honeybadger embedded in SmartBugs.
A problem that will remain is that Honeybadger may stumble across instructions that newer Solidity compilers generate that did not exist before and that Honeybadger therefore does not know how to handle (you will get a corresponding error message).
